"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
from itertools import *

N = 4000000

def fib_iter():
    a = b = 1
    while True:
        yield b
        a, b = b, a+b
        
        
assert sum(ifilter(lambda x: x % 2 == 0, 
            takewhile(lambda x: x <= N, 
                        fib_iter()))) == 4613732
                        
        